# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6551c73b726c287289627d5cdf88a90b8e1ab272716432b1a98b2e7707a7f009a213c3adb073d5eebad19940709992bb548449b37845da2c5188faecea6a6668

test:
  secret_key_base: 4b9a92c15396bd597cdc1f0c2d941d0ce988ffa2a4cbb593aa95f2decadf502503491530a1c5e36e2b32b1e342278cd9875f2e557e7b58d9c96b627335ed778a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
